### ISSUE TITLE
Is it possible to remove gcc dependency and how ?

### ISSUE THREAD

**Issue by GunGunGun** [wuhan005/Houki#2]
Hi, great project and I learned a lot from your project! But with gcc dependency the compile time is too long, I want to get rid of it but I'm new to Go so can you let me know what and which module do I need to remove to remove gcc requirement ? I just want a pure Go mitmproxy to recreate the mitmproxy from Python. Thanks!

**Comment by wuhan005** [comment]
Thanks for your feedback!

This project needs GCC because it uses SQLite as the backend database. The SQLite driver is `github.com/mattn/go-sqlite3` which needs CGO enabled and a GCC compile present.

The way to solve this problem is to use a pure-Go SQLite driver like `gitlab.com/cznic/sqlite`. I'll try to replace the current SQLite driver with this one.

**Comment by GunGunGun** [comment]
> Thanks for your feedback!
> 
> This project needs GCC because it uses SQLite as the backend database. The SQLite driver is `github.com/mattn/go-sqlite3` which needs CGO enabled and a GCC compile present.
> 
> The way to solve this problem is to use a pure-Go SQLite driver like `gitlab.com/cznic/sqlite`. I'll try to replace the current SQLite driver with this one.

Thank you very for the quick response! And yes, if it's possible I hope you can replace the gcc sqlite one with the native one!

I tried Houki for a while and I really loved this piece of software, web interface for managing ruleset is great and the ruleset is very familiar to me because it's very close to Proximitron/Proxidomo's syntax, I hope you'll continue to update it!

**Comment by wuhan005** [comment]
I've replaced the SQLite driver in this PR. https://github.com/wuhan005/Houki/pull/3

Now you can pull the latest commit and build with `CGO_ENABLED=0` to disable CGO.

**Comment by GunGunGun** [comment]
> I've replaced the SQLite driver in this PR. #3
> 
> Now you can pull the latest commit and build with `CGO_ENABLED=0` to disable CGO.

Thanks very much, I've successfully built Houki without gcc, build time is much faster!

Now the topic can be closed.
